= Andraste Framework Overview
:author: MeFisto94
:revnumber: 1.1
:revdate: 2024/05/02

== What is Andraste?
Andraste, at it's core, is a generic modding framework, aiming to bring a modern
toolset into old (DX 9) footnote:[Even older games may also work, but a lot of
the features (such as the in-game overlay) have been written against Direct X 9]
and modern games alike.
It does so by injecting a .NET FX Runtime into native applications, allowing us
to code the framework in a safe language (C#), which even opens up the
possibility to write code modifications in .NET languages, that interface
seamlessly with the native code of the game.

== Getting Started
Starting with Version 0.2.2, Andraste comes with a GUI Launcher that should be your preferred way of launching applications
and managing the related mods and framework versions. You should only have to use the CLI launcher when having to 
embed Andraste into a different (game specific) launcher or adding your modpack as a steam foreign game.

=== Launching Games using the generic UI Launcher
See xref:getting-started/ui-launcher.adoc[here] for more information about the UI Launcher

=== Launching Games using the generic CLI Launcher
If you really want to use the generic CLI Launcher, see it's dedicated subpage xref:cli-launcher.adoc[here]


=== Creating a first mod
See xref:getting-started/creating-the-first-mod.adoc[here] for a step-by-step tutorial on
creating modifications (i.e. non code changes).

See xref:getting-started/creating-the-first-plugin.adoc[here] for a step-by-step tutorial on
creating plugins (i.e. code changes).
