= The ModInformation (mod.json file)
:author: MeFisto94
:revnumber: 1.0
:revdate: 2024/09/09

NOTE: The Information on this page may be out-of-date and is rather meant as
a general guidance instead of an exhaustive format description.
If you need to go beyond that, visit https://github.com/AndrasteFramework/Shared/blob/master/ModManagement/Json/ModInformation.cs
for the actual in-code data structure.

== How it works
In order for Andraste to correctly load and apply your mod, it needs to know
the required metadata, such as author, mod-name (slug), versions and dependencies.
This, as well as what to actually do with the mod, is defined in the `ModInformation`.

This information is stored in the `mod.json` file, that has to be in the root
level folder of your mod directory.

Before the following sections go into detail, here is an exemplaric `mod.json`:

```
{
    "slug": "andraste-example",
    "name": "Andraste Example Mod",
    "displayVersion": "1.0.0",
    "semanticVersion": "1.0.0",
    "authors": ["MeFisto94", "redd"],
    "description": "An exemplaric mod for aspiring Andraste developers",
    "configurations": {
        "default": {
            "features": {
                "andraste.builtin.vfs": {
                    "directories": [
                        "mod-data/"
                    ],
                    "files": {}
                }
            }
        }
    },
    "dependencies": {
        "my-other-mod": "^1.2.3"
    }
}
```

=== The Metadata Section
As you can see, the mod information is a json object where the first few keys
are very self explanatory:
`name`, `description`, `authors` (an array!), `displayVersion` and `semanticVersion`.

TIP: `displayVersion`, as opposed to the `semanticVersion` field, only has to be human readable.
It doesn't have to be machine readable, i.e. you could version your mod whatever you like!

The `semanticVersion` is a version format in https://semver.org/[Semantic] format.
This ensures mods can specify dependencies on each other with version ranges and also
helps for future mod repositories to be able to reason about auto updating mods.
See https://docs.npmjs.com/about-semantic-versioning#incrementing-semantic-versions-in-published-packages[here]
for a recommendation of how to keep your version numbers according to SemVer.

The `slug` is also very intuitive, but it still may need some explanation:
The slug is basically a machine readable and path friendly name of your mod.
The name of your mod folder should also equal your `slug`.
It is used as a unique indentifier of your mod and is used both by Andraste
internally and for cross-mod references or potential future features such as
mod repositories and mod packs.

NOTE: To be path friendly, the slug should be all lowercase, alphanumerical characters and hyphens only. It is especially forbidden to prefix the slug
with an `@` or using forward slashes, as that is is reserved for other
uses, such as `@game/pinball` and `@andraste/core`

=== The Configuration Section
The configuration section allows the user to choose different _configurations_
of your mod, tailored to their needs.
This can range from multiple quality levels, to gameplay relevant changes.

NOTE: Since the Mod Information is declarative, configurations are currently the only way of making your mod configurable/providing settings.
If you have good ideas on how that situation could be improved, feel free to get
in contact with us.

NOTE: Currently, Andraste only supports exactly one configuration (this is a
limitation of the Launcher). Furthermore that configuration should be called
`default`. In general, there should always be a configuration called `default`.

=== The Feature Consumption Declaration
In order to declare, what your mod requires or provides, Andraste uses the
concept of `features`.
Every mod configures (_consumes_) features that are either provided by other
_plugins_ (code mods) or Andraste (_builtin_).

In the above example you can see how the `andraste.builtin.vfs` feature is used.
This feature is very commonly used, since it provides mods with a way to replace
game files at runtime (which is what even the most basic mods need).

The content of the feature's json object is completely dependent on the feature.

=== Dependencies
Whenever you want to express that your mod requires the presence of another mod,
you use the dependencies field for that. If you have a programming background,
this will feel natural to you.

In Andraste, the dependencies field is key-value map, mapping the required
dependency's slug to a version number _range_.
The version range is following the https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept[npm flavour]
of semantic version ranges. As such, the above example of `^1.2.3` means:
At least 1.2.3, but also every minor version upgrades (e.g. `1.9.9`).

This is also the most common dependency type you want, as minor releases
are promising to add new features without breaking backward compatibility,
so the only release of `my-other-mod` that *could* actively break your
`andraste-example` is starting with `2.0.0`

As outlined above, there are, similar to npm, namespaced dependencies,
that should not be occupied by user mods. Instead, those will be _provided_
at runtime based on the mod framework. Two examples of those namespaces are
`@game`, which can be used to specify dependencies on certain game versions
and `@andraste`, for andraste components.
